
SELECT (C.CITY::text || ','::text) || CY.COUNTRY AS STORE,
	F.TITLE,
	SUM(P.AMOUNT),
	S.STORE_ID
FROM PAYMENT P
JOIN RENTAL R ON P.RENTAL_ID = R.RENTAL_ID
JOIN INVENTORY I ON R.INVENTORY_ID = I.INVENTORY_ID
JOIN STORE S ON I.STORE_ID = S.STORE_ID
JOIN FILM F ON I.FILM_ID = F.FILM_ID
JOIN ADDRESS A ON S.ADDRESS_ID = A .ADDRESS_ID
JOIN CITY C ON A.CITY_ID = C.CITY_ID
JOIN COUNTRY CY ON C.COUNTRY_ID = CY.COUNTRY_ID

GROUP BY F.TITLE,
	C.CITY,
	CY.COUNTRY,
	S.STORE_ID

ORDER BY SUM(P.AMOUNT) DESC


